apiVersion: v1 # kubernetes api version
kind: PersistentVolumeClaim #the type of the object
metadata:
  name: MYAPP
  namespace: default
  labels:
    app: MYAPP
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: example-claim
# spec:
#   storageClassName: hostpath
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Mi